run_name: 1B
base_model_name: meta-llama/Llama-3.2-1B-Instruct
test_ratio: 0.002
batch_size: 8
accumulate_grad_batches: 2
dataset_names:
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/tinycodepython:3"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/pythonalpaca:3"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/opencoder"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/opencoder2:6"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/magicoder:6"

  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/openorca"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/openplatypus:20"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/ifevallike:10"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/gsm8k:20"
  
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/metamathqa:2"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/openr1math:2"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/mathgpt:2"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/mathinstruct:2"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/mathplus"

  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/narrativeqa:4"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/hotpotqa:2"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/mrqa:2"

  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/scienceqa:0.3"
  - "/data/data_persistent1/jingyu/hamburger/decreasing_v2/openmathinstruct2:0.2"
